package Logica;
// Generated 24-nov-2013 23:28:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Spaarkaart generated by hbm2java
 */
public class Spaarkaart  implements java.io.Serializable {


     private int kaartnr;
     private Account account;
     private String naamhouder;
     private Set aankoops = new HashSet(0);

    public Spaarkaart() {
    }

	
    public Spaarkaart(int kaartnr, Account account) {
        this.kaartnr = kaartnr;
        this.account = account;
    }
    public Spaarkaart(int kaartnr, Account account, String naamhouder, Set aankoops) {
       this.kaartnr = kaartnr;
       this.account = account;
       this.naamhouder = naamhouder;
       this.aankoops = aankoops;
    }
   
    public int getKaartnr() {
        return this.kaartnr;
    }
    
    public void setKaartnr(int kaartnr) {
        this.kaartnr = kaartnr;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getNaamhouder() {
        return this.naamhouder;
    }
    
    public void setNaamhouder(String naamhouder) {
        this.naamhouder = naamhouder;
    }
    public Set getAankoops() {
        return this.aankoops;
    }
    
    public void setAankoops(Set aankoops) {
        this.aankoops = aankoops;
    }




}


