package Logica;
// Generated 24-nov-2013 23:28:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Vestiging generated by hbm2java
 */
public class Vestiging  implements java.io.Serializable {


     private VestigingId id;
     private Winkel winkel;
     private String adres;
     private Set aankoops = new HashSet(0);

    public Vestiging() {
    }

	
    public Vestiging(VestigingId id, Winkel winkel) {
        this.id = id;
        this.winkel = winkel;
    }
    public Vestiging(VestigingId id, Winkel winkel, String adres, Set aankoops) {
       this.id = id;
       this.winkel = winkel;
       this.adres = adres;
       this.aankoops = aankoops;
    }
   
    public VestigingId getId() {
        return this.id;
    }
    
    public void setId(VestigingId id) {
        this.id = id;
    }
    public Winkel getWinkel() {
        return this.winkel;
    }
    
    public void setWinkel(Winkel winkel) {
        this.winkel = winkel;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public Set getAankoops() {
        return this.aankoops;
    }
    
    public void setAankoops(Set aankoops) {
        this.aankoops = aankoops;
    }




}


