package Logica;
// Generated 24-nov-2013 23:28:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Winkel generated by hbm2java
 */
public class Winkel  implements java.io.Serializable {


     private String winkelnaam;
     private Account account;
     private String paswoord;
     private Set artikels = new HashSet(0);
     private Set vestigings = new HashSet(0);

    public Winkel() {
    }

	
    public Winkel(String winkelnaam) {
        this.winkelnaam = winkelnaam;
    }
    public Winkel(String winkelnaam, Account account, String paswoord, Set artikels, Set vestigings) {
       this.winkelnaam = winkelnaam;
       this.account = account;
       this.paswoord = paswoord;
       this.artikels = artikels;
       this.vestigings = vestigings;
    }
   
    public String getWinkelnaam() {
        return this.winkelnaam;
    }
    
    public void setWinkelnaam(String winkelnaam) {
        this.winkelnaam = winkelnaam;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getPaswoord() {
        return this.paswoord;
    }
    
    public void setPaswoord(String paswoord) {
        this.paswoord = paswoord;
    }
    public Set getArtikels() {
        return this.artikels;
    }
    
    public void setArtikels(Set artikels) {
        this.artikels = artikels;
    }
    public Set getVestigings() {
        return this.vestigings;
    }
    
    public void setVestigings(Set vestigings) {
        this.vestigings = vestigings;
    }




}


